# Generated by Django 5.0.2 on 2024-05-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tags_tag_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('update_title', 'Can update the title of the blog'), ('update_content', 'Can update the content of blog')]},
        ),
    ]
